baseURL: https://dhar01.github.io
title: Loknath's Space
paginate: 5
theme: PaperMod

defaultContentLanguage: en

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: search
          name: Search
          url: /search/
          weight: 1
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        - identifier: about
          name: About
          url: /about/
          weight: 4

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    title: Loknath's Space
    description: Share / Summary / Record 
    keywords: [Blog, Portfolio]
    author: Me

    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    displayFullLangName: true

    ShowReadingTime: true
    ShowBreadCrumbs: false 
    ShowPostNavLinks: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: I'm Loknath Dhar, a Linux Enthusiast.<br>Talk to me about Infosec, Linux

    socialIcons:
        - name: LinkedIn
          url: "https://www.linkedin.com/in/dhar01/" 
        - name: GitHub
          url: "https://github.com/dhar01"
        - name: Telegram
          url: "https://t.me/Dhar01"
        - name: rss
          url: "index.xml"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: [ "title", "permalink", "summary", "content" ]

taxonomies:
    category: categories
    tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
